global:
  resolve_timeout: 5m # If resolved alerts not sent (for any reason), it saves alerts for this time and send
  smtp_smarthost: "mailhog:1025"
  smtp_from: "alertmanager@example.com"
  smtp_hello: "localhost"
  smtp_require_tls: false

route:
  receiver: email
  group_wait: 10s # Wait time to collect all alerts
  group_interval: 10s # Interval to send alert after each group_wait
  repeat_interval: 15s # Repeat interval to send alert after each send
  group_by: ['instance']
  routes:
    - receiver: email
      matchers:
        - severity="critical"

receivers:
  - name: email
    email_configs:
      - to: "test@example.com"
        send_resolved: true