global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "metric-app"
    static_configs:
      - targets: ["metric-app:8085"]
